
[functions.minha_funcao]
enabled = true
verify_jwt = true
import_map = "./functions/minha_funcao/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/minha_funcao/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/minha_funcao/*.html" ]

[functions.minha_funcao2]
enabled = true
verify_jwt = true
import_map = "./functions/minha_funcao2/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/minha_funcao2/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/minha_funcao2/*.html" ]

[functions.manager_profissional]
enabled = true
verify_jwt = true
import_map = "./functions/manager_profissional/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/manager_profissional/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/manager_profissional/*.html" ]
